# Generated by Django 4.1 on 2022-08-29 18:58

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(height_field='image_height', null=True, upload_to=products.models.product_image_upload, width_field='image_width'),
        ),
        migrations.AddField(
            model_name='products',
            name='image_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='image_width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
