# Generated by Django 4.1 on 2022-08-29 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_image_products_image_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
